### PR TITLE
Add update topic translation command

### PR DESCRIPTION
**Pull request by smreichling**
This API endpoint is documented here: http://dev.desk.com/API/topics/#translations-update.

### CODE REVIEW

**Comment by smreichling** [comment]
Looks like CI failed because the latest version of Mockery doesn't support PHP 5.3: https://github.com/padraic/mockery#prerequisites. Does this library need to continue to support 5.3?

**Comment by bradfeehan** [comment]
The tests fail because Composer is still using `composer.json` from the `master` branch (even though it specifies a specific SHA, it uses the `composer.json` from the HEAD of the branch 😢)

Would you like to check if it can be fixed by changing the Mockery dependency version to `dev-0.9#3bd6f1712642838b4c0524d3a47359940df72e80`? I want to use this exact SHA, and I'm guessing this is why Mockery provided a 0.9 branch.

I would like to maintain PHP 5.3 compatibility -- there's a few people running this on older versions, I don't want to cause any issues, I don't really maintain this library very much any more.

**Comment by smreichling** [comment]
Thanks for the suggestion, unfortunately that didn't work either. 😞 

Can't spend more time on this now but I'll take another look next week.

**Comment by smreichling** [comment]
I tried a couple different options but couldn't find a way to pull in that specific hash of mockery. 😢 

I ended up working around this missing API on my side so I no longer need this change, so I'm going to close this PR.

**Pull request closed without merging**
